from typing import Dict


THEMES: Dict[str, dict] = {
    "AI & Software": {
        "proxy": "QQQ",
        "benchmark": "SPY",
        "members": ["QQQ", "XLK", "MSFT", "NVDA", "AVGO", "GOOGL", "AMZN"],
        "etfs": ["QQQ", "XLK", "SMH", "SOXX"],
        "leaders": ["MSFT", "NVDA", "AVGO", "ASML"],
        "drivers": [
            "Datacenter capex",
            "GPU-efterspørgsel",
            "Enterprise software spending",
            "Cloud-vækst",
            "Produktivitetsinvesteringer",
        ],
        "headwinds": [
            "Høje multipler",
            "Capex-normalisering",
            "Regulatoriske risici",
            "AI-monetisering langsommere end ventet",
        ],
        "macro_series": {
            "rate_10y": "DGS10",
            "inflation": "CPIAUCSL",
            "industrial": "INDPRO",
        },
        "description": "Temaet dækker software, hyperscalers, AI-infrastruktur og halvleder-efterspørgsel drevet af datacenterudbygning og enterprise adoption.",
    },
    "Semiconductors": {
        "proxy": "SOXX",
        "benchmark": "SPY",
        "members": ["SOXX", "SMH", "NVDA", "AVGO", "AMD", "TSM", "ASML"],
        "etfs": ["SOXX", "SMH"],
        "leaders": ["NVDA", "AVGO", "TSM", "ASML"],
        "drivers": [
            "AI-servere",
            "Foundry-kapacitet",
            "Memory-cyklus",
            "Industrikapacitet",
            "Elektrificering",
        ],
        "headwinds": [
            "Cyklicitet",
            "Geopolitik",
            "Overkapacitet",
            "Kundeforlager",
        ],
        "macro_series": {
            "industrial": "INDPRO",
            "rate_10y": "DGS10",
            "usd": "DTWEXBGS",
        },
        "description": "Halvledertemaet drives af AI, datacenterkapacitet, foundry-økonomi og global industriefterspørgsel.",
    },
    "Defense/Aerospace": {
        "proxy": "ITA",
        "benchmark": "SPY",
        "members": ["ITA", "XAR", "LMT", "NOC", "RTX", "GD"],
        "etfs": ["ITA", "XAR"],
        "leaders": ["LMT", "NOC", "RTX", "GD"],
        "drivers": [
            "Forsvarsbudgetter",
            "Genopbygning af lagre",
            "Geopolitisk spænding",
            "NATO-spending",
        ],
        "headwinds": [
            "Politisk budgetskifte",
            "Forsinkede kontrakter",
            "Forsyningskædeproblemer",
        ],
        "macro_series": {
            "rate_10y": "DGS10",
            "industrial": "INDPRO",
            "oil": "DCOILWTICO",
        },
        "description": "Defense/Aerospace nyder støtte fra stigende forsvarsbudgetter, lagergenopbygning og længerevarende sikkerhedspolitiske spændinger.",
    },
    "Clean Energy": {
        "proxy": "ICLN",
        "benchmark": "SPY",
        "members": ["ICLN", "PBW", "TAN", "ENPH", "FSLR", "VWS.CO"],
        "etfs": ["ICLN", "PBW", "TAN"],
        "leaders": ["FSLR", "ENPH", "VWS.CO"],
        "drivers": [
            "Subsidier",
            "Netudbygning",
            "Lavere teknologiomkostninger",
            "Elforbrug og elektrificering",
        ],
        "headwinds": [
            "Høje renter",
            "Projektforsinkelser",
            "Volatile komponentpriser",
            "Politisk usikkerhed",
        ],
        "macro_series": {
            "rate_10y": "DGS10",
            "inflation": "CPIAUCSL",
            "oil": "DCOILWTICO",
        },
        "description": "Clean Energy er rentefølsomt og afhænger af subsidier, netudbygning og konkurrenceevne mod fossile alternativer.",
    },
    "Banks": {
        "proxy": "XLF",
        "benchmark": "SPY",
        "members": ["XLF", "JPM", "BAC", "WFC", "GS", "MS"],
        "etfs": ["XLF", "KBE"],
        "leaders": ["JPM", "GS", "MS"],
        "drivers": [
            "Rentekurve",
            "Kreditvækst",
            "Net interest margin",
            "Kapitalmarkedsaktivitet",
        ],
        "headwinds": [
            "Kreditforringelser",
            "Flad/inverteret kurve",
            "Regulatorisk pres",
        ],
        "macro_series": {
            "rate_10y": "DGS10",
            "rate_2y": "DGS2",
            "unemployment": "UNRATE",
        },
        "description": "Banker påvirkes især af rentekurven, kreditkvalitet og aktivitetsniveau i økonomien og kapitalmarkederne.",
    },
    "Gold": {
        "proxy": "GLD",
        "benchmark": "SPY",
        "members": ["GLD", "IAU", "NEM", "AEM"],
        "etfs": ["GLD", "IAU"],
        "leaders": ["NEM", "AEM"],
        "drivers": [
            "Reale renter",
            "USD-retning",
            "Inflationsforventninger",
            "Geopolitisk risiko",
        ],
        "headwinds": [
            "Stigende reale renter",
            "Stærk USD",
            "Lav risikofrygt",
        ],
        "macro_series": {
            "rate_10y": "DGS10",
            "inflation": "CPIAUCSL",
            "usd": "DTWEXBGS",
        },
        "description": "Guld fungerer ofte som hedge mod realrenter, dollarstyrke, inflationsfrygt og geopolitisk usikkerhed.",
    },
    "Electric Grid": {
        "proxy": "GRID",
        "benchmark": "SPY",
        "members": ["ETN", "ABB", "HUBB", "PWR", "GEV"],
        "etfs": ["GRID", "XLU"],
        "leaders": ["ETN", "ABB", "HUBB", "PWR"],
        "drivers": [
            "Netudbygning",
            "Elektrificering",
            "Datacenter-strømforbrug",
            "Grid modernization",
        ],
        "headwinds": [
            "Projektforsinkelser",
            "Regulatoriske barrierer",
            "Kapitalintensitet",
        ],
        "macro_series": {
            "industrial": "INDPRO",
            "rate_10y": "DGS10",
            "oil": "DCOILWTICO",
        },
        "description": "Electric Grid drives af netudbygning, elektrificering og stigende strømbehov fra industri og datacentre.",
    },
    "Robotics": {
        "proxy": "BOTZ",
        "benchmark": "SPY",
        "members": ["ISRG", "ABB", "ROK", "TER", "SYM"],
        "etfs": ["BOTZ", "ROBO"],
        "leaders": ["ISRG", "ABB", "ROK"],
        "drivers": [
            "Automatisering",
            "Produktivitetskrav",
            "Arbejdskraftmangel",
        ],
        "headwinds": [
            "Svag industrikonjunktur",
            "Capex-udsættelser",
            "Høje forventninger",
        ],
        "macro_series": {
            "industrial": "INDPRO",
            "rate_10y": "DGS10",
        },
        "description": "Robotics dækker industriel automation, kirurgisk robotik og produktivitetsdrevet teknologi.",
    },
    "Cybersecurity": {
        "proxy": "CIBR",
        "benchmark": "SPY",
        "members": ["CRWD", "PANW", "ZS", "FTNT", "CYBR", "OKTA"],
        "etfs": ["CIBR", "HACK"],
        "leaders": ["CRWD", "PANW", "FTNT"],
        "drivers": [
            "Stigende cybertrusler",
            "Compliance-krav",
            "Cloud security spend",
        ],
        "headwinds": [
            "Budgetpres hos kunder",
            "Høj konkurrence",
            "Multiple compression",
        ],
        "macro_series": {
            "rate_10y": "DGS10",
            "industrial": "INDPRO",
        },
        "description": "Cybersecurity støttes af stigende digitale trusler, cloud-udbredelse og regulatoriske krav.",
    },
    "Space Economy": {
        "proxy": "ARKX",
        "benchmark": "SPY",
        "members": ["RKLB", "LMT", "NOC", "IRDM"],
        "etfs": ["ARKX", "UFO"],
        "leaders": ["RKLB", "LMT", "NOC"],
        "drivers": [
            "Satellitter",
            "Opsendelser",
            "Forsvar og space overlap",
        ],
        "headwinds": [
            "Lav profitabilitet",
            "Højt kapitalbehov",
            "Teknologisk execution risk",
        ],
        "macro_series": {
            "industrial": "INDPRO",
            "rate_10y": "DGS10",
        },
        "description": "Space Economy dækker rumfart, satellitter, forsvarsrelateret space og nye launch-platforme.",
    },
    "Nuclear Renaissance": {
        "proxy": "URA",
        "benchmark": "SPY",
        "members": ["CCJ", "BWXT", "SMR", "OKLO", "NXE"],
        "etfs": ["URA", "URNM"],
        "leaders": ["CCJ", "BWXT", "SMR"],
        "drivers": [
            "Baseload power",
            "Datacenter-strømbehov",
            "Energisikkerhed",
        ],
        "headwinds": [
            "Politisk usikkerhed",
            "Projektforsinkelser",
            "Teknologisk modenhed",
        ],
        "macro_series": {
            "oil": "DCOILWTICO",
            "inflation": "CPIAUCSL",
            "rate_10y": "DGS10",
        },
        "description": "Nuclear Renaissance drives af behovet for stabil CO2-fri strøm og energisikkerhed.",
    },
    "Rare Earth Metals": {
        "proxy": "REMX",
        "benchmark": "SPY",
        "members": ["MP", "LYC", "UUUU"],
        "etfs": ["REMX"],
        "leaders": ["MP", "LYC"],
        "drivers": [
            "Forsyningssikkerhed",
            "Elektrificering",
            "Defense supply chains",
        ],
        "headwinds": [
            "Råvarepris-volatilitet",
            "Geopolitisk afhængighed",
            "Smalt marked",
        ],
        "macro_series": {
            "industrial": "INDPRO",
            "usd": "DTWEXBGS",
        },
        "description": "Rare Earth Metals dækker kritiske materialer til magneter, defense og elektrificering.",
    },
    "Healthcare AI": {
        "proxy": "ARKG",
        "benchmark": "SPY",
        "members": ["ISRG", "DXCM", "ILMN", "EXAS", "SYK", "TMO"],
        "etfs": ["ARKG", "IHI"],
        "leaders": ["ISRG", "SYK", "TMO"],
        "drivers": [
            "Diagnostik",
            "Automation i healthcare",
            "Data- og softwareforbedringer",
        ],
        "headwinds": [
            "Regulering",
            "Lang adoptionskurve",
            "Refusionsrisiko",
        ],
        "macro_series": {
            "rate_10y": "DGS10",
            "inflation": "CPIAUCSL",
        },
        "description": "Healthcare AI dækker automation, dataanalyse og AI-understøttet beslutningsstøtte i healthcare.",
    },
    "Autonomous Transport": {
        "proxy": "DRIV",
        "benchmark": "SPY",
        "members": ["TSLA", "MBLY", "NVDA", "GM", "RIVN"],
        "etfs": ["DRIV", "KARS"],
        "leaders": ["TSLA", "MBLY", "NVDA"],
        "drivers": [
            "ADAS",
            "Software-defined vehicles",
            "Autonomi og EV-konvergens",
        ],
        "headwinds": [
            "Regulatoriske barrierer",
            "Prispress",
            "Lav profitabilitet",
        ],
        "macro_series": {
            "industrial": "INDPRO",
            "oil": "DCOILWTICO",
            "rate_10y": "DGS10",
        },
        "description": "Autonomous Transport dækker førerløse systemer, ADAS og softwaredrevet mobilitet.",
    },
}